name: nuclear-fusion-analyzer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scipy>=1.7.0
  - jupyter>=1.0.0
  - jupyterlab>=3.2.0
  - pytest>=6.2.0
  - pyyaml>=6.0
  - h5py>=3.6.0
  - netcdf4>=1.5.8
  - xarray>=0.20.0
  - pip
  - pip:
    - tensorflow>=2.8.0
    - torch>=1.10.0
    - transformers>=4.15.0
    - plotly>=5.0.0
    - fastapi>=0.70.0
    - uvicorn>=0.15.0
    - pydantic>=1.8.0
    - loguru>=0.6.0
    - hydra-core>=1.1.0
    - streamlit>=1.15.0
    - dash>=2.7.0
    - bokeh>=2.4.0
    - pytest-cov>=3.0.0
    - pytest-mock>=3.6.0
    - black>=21.0.0
    - flake8>=4.0.0
    - mypy>=0.910
    - pre-commit>=2.15.0
    - ipywidgets>=7.6.0
    - sqlalchemy>=1.4.0
    - psycopg2-binary>=2.9.0
    - tqdm>=4.62.0
    - click>=8.0.0
    - requests>=2.26.0
    - python-dotenv>=0.19.0
    - radioactivedecay>=5.0.0