name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install

    - name: Run Black (formatting)
      run: poetry run black --check --diff src/ tests/

    - name: Run isort (import sorting)
      run: poetry run isort --check-only --diff src/ tests/

    - name: Run flake8 (linting)
      run: poetry run flake8 src/ tests/ --max-line-length=120

    - name: Run pylint
      run: poetry run pylint src/ --rcfile=.pylintrc

    - name: Run mypy (type checking)
      run: poetry run mypy src/ --config-file=mypy.ini

    - name: Run bandit (security)
      run: poetry run bandit -r src/ -f json -o bandit-results.json

    - name: Run safety (dependency security)
      run: poetry run safety check --json --output safety-results.json

    - name: Upload security results
      uses: actions/upload-artifact@v3
      with:
        name: security-results
        path: |
          bandit-results.json
          safety-results.json

  documentation:
    name: Documentation Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install --with docs

    - name: Build documentation
      run: |
        cd docs
        poetry run sphinx-build -b html . _build/html

    - name: Check documentation links
      run: |
        cd docs
        poetry run sphinx-build -b linkcheck . _build/linkcheck

    - name: Upload documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/_build/html/